modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
#logoFile=""
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
#credits=""
description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="swem"
    type="required"
    versionRange="[1.6.10,)"
    ordering="NONE"
    side="BOTH"

